### ISSUE TITLE
selenium ft whatsapp can anyone tell me what's wrong and how to fix it

### ISSUE THREAD

**Issue by cypriankoech** [cypriankoech/whatsapp-selenium#1]
from selenium import webdriver

dr = webdriver.Chrome()
dr.get('https://web.whatsapp.com/')

input("Enter anything after scanning the QR code:")

name = input("Enter the name of the group or user: ")
msg = input("Enter the message:")
count = int(input("Input the count: "))

input("Enter anything after scanning the QR code:")

person = dr.find_element_by_xpath('//span[@title ="{}"]'.format(name))
person.click()

msg_box = dr.find_element_by_class_name('_3u328 copyable-text selectable-textq')

for i in range(count):
	msg_box.send_keys(msg)
	button = dr.find_element_by_class_name('_3M-N-')
	button.click()

# Running this code via cmd I get these errors

C:\Users\cyprian\Desktop\whatsapp>python whatsapp.py

DevTools listening on ws://127.0.0.1:52522/devtools/browser/86cc91d5-e2c1-4412-9475-af4ddb6f6ab2
Enter the name: Shh
Enter the message: hello
Input the count: 1
Enter anything after scanning the QR code:
Traceback (most recent call last):
---------------------------------------------------------------------------------------------------------------
  File "whatsapp.py", line 12, in <module>
    person = driver.find_element_by_xpath('//span[@title ="{}"]'.format(name))
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Program Files\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//span[@title ="Shh"]"}
  (Session info: chrome=73.0.3683.86)
  (Driver info: chromedriver=2.46.628402 (536cd7adbad73a3783fdc2cab92ab2ba7ec361e1),platform=Windows NT 10.0.18363 x86_64)
---------------------------------------------------------------------------------------------------------------

**Comment by cypriankoech** [comment]
you'll have to replace the button class and user class to test it
Also for reference video is https://youtu.be/5hr0IdVM7Qg
